In [32]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np

In [33]:
covid_data_csv = Path("COVID-19_Deaths_by_Sex_and_Age_20240328.csv")
covid_data_df = pd.read_csv(covid_data_csv)

In [34]:
covid_data_df.head()

,Data As Of,Start Date,End Date,Group,Year,Month,State,Sex,Age Group,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Pneumonia and COVID-19 Deaths,Influenza Deaths,"Pneumonia, Influenza, or COVID-19 Deaths",Footnote
0,09/27/2023,01/01/2020,09/23/2023,By Total,NaN,NaN,United States,All Sexes,All Ages,1146774.0,12303399.0,1162844.0,569264.0,22229.0,1760095.0,NaN
1,09/27/2023,01/01/2020,09/23/2023,By Total,NaN,NaN,United States,All Sexes,Under 1 year,519.0,73213.0,1056.0,95.0,64.0,1541.0,NaN
2,09/27/2023,01/01/2020,09/23/2023,By Total,NaN,NaN,United States,All Sexes,0-17 years,1696.0,130970.0,2961.0,424.0,509.0,4716.0,NaN
3,09/27/2023,01/01/2020,09/23/2023,By Total,NaN,NaN,United States,All Sexes,1-4 years,285.0,14299.0,692.0,66.0,177.0,1079.0,NaN
4,09/27/2023,01/01/2020,09/23/2023,By Total,NaN,NaN,United States,All Sexes,5-14 years,509.0,22008.0,818.0,143.0,219.0,1390.0,NaN

In [4]:
columns = ["Data As Of", "Start Date", "End Date",	"Group", "Year", "Month", "State", "Sex", "Age Group",
           "COVID-19 Deaths", "Total Deaths", "Pneumonia Deaths", "Pneumonia and COVID-19 Deaths", "Influenza Deaths",
           "Pneumonia, Influenza, or COVID-19 Deaths"]
covid_nj_df = covid_data_df.loc[covid_data_df["State"] == "New Jersey", columns]

In [5]:
covid_nj_df

,Data As Of,Start Date,End Date,Group,Year,Month,State,Sex,Age Group,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Pneumonia and COVID-19 Deaths,Influenza Deaths,"Pneumonia, Influenza, or COVID-19 Deaths"
1581,09/27/2023,01/01/2020,09/23/2023,By Total,NaN,NaN,New Jersey,All Sexes,All Ages,35691.0,312963.0,31031.0,17287.0,363.0,49766.0
1582,09/27/2023,01/01/2020,09/23/2023,By Total,NaN,NaN,New Jersey,All Sexes,Under 1 year,14.0,1140.0,19.0,NaN,NaN,32.0
1583,09/27/2023,01/01/2020,09/23/2023,By Total,NaN,NaN,New Jersey,All Sexes,0-17 years,28.0,1935.0,43.0,NaN,NaN,69.0
1584,09/27/2023,01/01/2020,09/23/2023,By Total,NaN,NaN,New Jersey,All Sexes,1-4 years,NaN,210.0,NaN,0.0,NaN,NaN
1585,09/27/2023,01/01/2020,09/23/2023,By Total,NaN,NaN,New Jersey,All Sexes,5-14 years,NaN,301.0,12.0,NaN,NaN,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87205,09/27/2023,09/01/2023,09/23/2023,By Month,2023.0,9.0,New Jersey,Female,50-64 years,NaN,208.0,NaN,NaN,0.0,10.0
87206,09/27/2023,09/01/2023,09/23/2023,By Month,2023.0,9.0,New Jersey,Female,55-64 years,NaN,168.0,NaN,NaN,0.0,10.0
87207,09/27/2023,09/01/2023,09/23/2023,By Month,2023.0,9.0,New Jersey,Female,65-74 years,NaN,269.0,12.0,0.0,0.0,14.0
87208,09/27/2023,09/01/2023,09/23/2023,By Month,2023.0,9.0,New Jersey,Female,75-84 years,14.0,469.0,31.0,NaN,0.0,39.0
87209,09/27/2023,09/01/2023,09/23/2023,By Month,2023.0,9.0,New Jersey,Female,85 years and over,23.0,810.0,41.0,NaN,0.0,56.0

In [35]:
columns2 = ["Start Date", "End Date", "State", "Sex", "Age Group", "Year", "Month", "COVID-19 Deaths", "Total Deaths", "Pneumonia Deaths", "Pneumonia and COVID-19 Deaths", "Influenza Deaths",
           "Pneumonia, Influenza, or COVID-19 Deaths"]
#creating data fram for males
male_df = covid_nj_df.loc[covid_nj_df["Sex"] == "Male", columns2]
male_df

,Start Date,End Date,State,Sex,Age Group,Year,Month,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Pneumonia and COVID-19 Deaths,Influenza Deaths,"Pneumonia, Influenza, or COVID-19 Deaths"
1598,01/01/2020,09/23/2023,New Jersey,Male,All Ages,NaN,NaN,19376.0,158472.0,17012.0,9677.0,188.0,26886.0
1599,01/01/2020,09/23/2023,New Jersey,Male,Under 1 year,NaN,NaN,NaN,648.0,13.0,NaN,0.0,18.0
1600,01/01/2020,09/23/2023,New Jersey,Male,0-17 years,NaN,NaN,13.0,1133.0,25.0,NaN,NaN,37.0
1601,01/01/2020,09/23/2023,New Jersey,Male,1-4 years,NaN,NaN,NaN,110.0,NaN,0.0,0.0,NaN
1602,01/01/2020,09/23/2023,New Jersey,Male,5-14 years,NaN,NaN,NaN,167.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
87188,09/01/2023,09/23/2023,New Jersey,Male,50-64 years,2023.0,9.0,NaN,270.0,NaN,NaN,0.0,NaN
87189,09/01/2023,09/23/2023,New Jersey,Male,55-64 years,2023.0,9.0,NaN,206.0,NaN,NaN,0.0,NaN
87190,09/01/2023,09/23/2023,New Jersey,Male,65-74 years,2023.0,9.0,NaN,374.0,23.0,NaN,0.0,28.0
87191,09/01/2023,09/23/2023,New Jersey,Male,75-84 years,2023.0,9.0,13.0,476.0,38.0,NaN,0.0,45.0
87192,09/01/2023,09/23/2023,New Jersey,Male,85 years and over,2023.0,9.0,19.0,483.0,32.0,NaN,0.0,44.0

In [36]:
female_df = covid_nj_df.loc[covid_nj_df["Sex"] == "Female", columns2]
female_df

,Start Date,End Date,State,Sex,Age Group,Year,Month,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Pneumonia and COVID-19 Deaths,Influenza Deaths,"Pneumonia, Influenza, or COVID-19 Deaths"
1615,01/01/2020,09/23/2023,New Jersey,Female,All Ages,NaN,NaN,16315.0,154491.0,14019.0,7610.0,175.0,22880.0
1616,01/01/2020,09/23/2023,New Jersey,Female,Under 1 year,NaN,NaN,NaN,492.0,NaN,NaN,NaN,14.0
1617,01/01/2020,09/23/2023,New Jersey,Female,0-17 years,NaN,NaN,15.0,802.0,18.0,NaN,NaN,32.0
1618,01/01/2020,09/23/2023,New Jersey,Female,1-4 years,NaN,NaN,NaN,100.0,NaN,0.0,NaN,NaN
1619,01/01/2020,09/23/2023,New Jersey,Female,5-14 years,NaN,NaN,NaN,134.0,NaN,NaN,0.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
87205,09/01/2023,09/23/2023,New Jersey,Female,50-64 years,2023.0,9.0,NaN,208.0,NaN,NaN,0.0,10.0
87206,09/01/2023,09/23/2023,New Jersey,Female,55-64 years,2023.0,9.0,NaN,168.0,NaN,NaN,0.0,10.0
87207,09/01/2023,09/23/2023,New Jersey,Female,65-74 years,2023.0,9.0,NaN,269.0,12.0,0.0,0.0,14.0
87208,09/01/2023,09/23/2023,New Jersey,Female,75-84 years,2023.0,9.0,14.0,469.0,31.0,NaN,0.0,39.0
87209,09/01/2023,09/23/2023,New Jersey,Female,85 years and over,2023.0,9.0,23.0,810.0,41.0,NaN,0.0,56.0

In [51]:
total_mcovid_deaths = pd.DataFrame(male_df.loc[male_df['Age Group'] == "All Ages",:])

total_mcovid_deaths

#dates_end = total_mcovid_deaths['End Date'].count()
#total_deaths = dates_mcovid_deaths['Total Deaths'].sum()
#dates_end
#total_deaths

,Start Date,End Date,State,Sex,Age Group,Year,Month,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Pneumonia and COVID-19 Deaths,Influenza Deaths,"Pneumonia, Influenza, or COVID-19 Deaths"
1598,01/01/2020,09/23/2023,New Jersey,Male,All Ages,NaN,NaN,19376.0,158472.0,17012.0,9677.0,188.0,26886.0
9095,01/01/2020,12/31/2020,New Jersey,Male,All Ages,2020.0,NaN,9881.0,48588.0,7353.0,4981.0,92.0,12338.0
9146,01/01/2021,12/31/2021,New Jersey,Male,All Ages,2021.0,NaN,5340.0,42570.0,4787.0,2871.0,NaN,7257.0
9197,01/01/2022,12/31/2022,New Jersey,Male,All Ages,2022.0,NaN,3490.0,40977.0,3392.0,1585.0,66.0,5358.0
9248,01/01/2023,09/23/2023,New Jersey,Male,All Ages,2023.0,NaN,665.0,26337.0,1480.0,240.0,29.0,1933.0
84932,01/01/2020,01/31/2020,New Jersey,Male,All Ages,2020.0,1.0,0.0,3444.0,199.0,0.0,24.0,223.0
84983,02/01/2020,02/29/2020,New Jersey,Male,All Ages,2020.0,2.0,0.0,3007.0,176.0,0.0,28.0,204.0
85034,03/01/2020,03/31/2020,New Jersey,Male,All Ages,2020.0,3.0,413.0,4047.0,489.0,214.0,24.0,711.0
85085,04/01/2020,04/30/2020,New Jersey,Male,All Ages,2020.0,4.0,4900.0,9317.0,2905.0,2438.0,13.0,5375.0
85136,05/01/2020,05/31/2020,New Jersey,Male,All Ages,2020.0,5.0,1718.0,4911.0,1084.0,886.0,NaN,1918.0
85187,06/01/2020,06/30/2020,New Jersey,Male,All Ages,2020.0,6.0,389.0,3175.0,309.0,176.0,0.0,522.0
85238,07/01/2020,07/31/2020,New Jersey,Male,All Ages,2020.0,7.0,187.0,3108.0,222.0,82.0,0.0,327.0
85289,08/01/2020,08/31/2020,New Jersey,Male,All Ages,2020.0,8.0,86.0,2976.0,167.0,38.0,0.0,215.0
85340,09/01/2020,09/30/2020,New Jersey,Male,All Ages,2020.0,9.0,83.0,2969.0,202.0,41.0,0.0,244.0
85391,10/01/2020,10/31/2020,New Jersey,Male,All Ages,2020.0,10.0,138.0,3146.0,220.0,64.0,0.0,294.0
85442,11/01/2020,11/30/2020,New Jersey,Male,All Ages,2020.0,11.0,580.0,3718.0,454.0,302.0,0.0,732.0
85493,12/01/2020,12/31/2020,New Jersey,Male,All Ages,2020.0,12.0,1387.0,4770.0,926.0,740.0,NaN,1573.0
85544,01/01/2021,01/31/2021,New Jersey,Male,All Ages,2021.0,1.0,1384.0,4706.0,945.0,752.0,0.0,1577.0
85595,02/01/2021,02/28/2021,New Jersey,Male,All Ages,2021.0,2.0,840.0,3883.0,596.0,440.0,0.0,996.0
85646,03/01/2021,03/31/2021,New Jersey,Male,All Ages,2021.0,3.0,560.0,3744.0,446.0,285.0,0.0,721.0
85697,04/01/2021,04/30/2021,New Jersey,Male,All Ages,2021.0,4.0,556.0,3604.0,447.0,305.0,0.0,698.0
85748,05/01/2021,05/31/2021,New Jersey,Male,All Ages,2021.0,5.0,282.0,3164.0,283.0,143.0,NaN,423.0
85799,06/01/2021,06/30/2021,New Jersey,Male,All Ages,2021.0,6.0,88.0,3110.0,168.0,43.0,0.0,213.0
85850,07/01/2021,07/31/2021,New Jersey,Male,All Ages,2021.0,7.0,66.0,2973.0,190.0,41.0,0.0,215.0
85901,08/01/2021,08/31/2021,New Jersey,Male,All Ages,2021.0,8.0,187.0,3227.0,247.0,95.0,0.0,339.0
85952,09/01/2021,09/30/2021,New Jersey,Male,All Ages,2021.0,9.0,349.0,3345.0,388.0,222.0,0.0,515.0
86003,10/01/2021,10/31/2021,New Jersey,Male,All Ages,2021.0,10.0,300.0,3537.0,369.0,176.0,0.0,493.0
86054,11/01/2021,11/30/2021,New Jersey,Male,All Ages,2021.0,11.0,199.0,3353.0,290.0,105.0,0.0,384.0
86105,12/01/2021,12/31/2021,New Jersey,Male,All Ages,2021.0,12.0,529.0,3924.0,418.0,264.0,0.0,683.0
86156,01/01/2022,01/31/2022,New Jersey,Male,All Ages,2022.0,1.0,1680.0,5350.0,1031.0,857.0,NaN,1854.0
86207,02/01/2022,02/28/2022,New Jersey,Male,All Ages,2022.0,2.0,474.0,3469.0,409.0,250.0,NaN,636.0
86258,03/01/2022,03/31/2022,New Jersey,Male,All Ages,2022.0,3.0,113.0,3225.0,187.0,53.0,0.0,247.0
86309,04/01/2022,04/30/2022,New Jersey,Male,All Ages,2022.0,4.0,83.0,3035.0,174.0,28.0,0.0,229.0
86360,05/01/2022,05/31/2022,New Jersey,Male,All Ages,2022.0,5.0,143.0,3249.0,175.0,46.0,NaN,276.0
86411,06/01/2022,06/30/2022,New Jersey,Male,All Ages,2022.0,6.0,105.0,2995.0,176.0,42.0,NaN,240.0
86462,07/01/2022,07/31/2022,New Jersey,Male,All Ages,2022.0,7.0,135.0,3184.0,166.0,33.0,NaN,270.0
86513,08/01/2022,08/31/2022,New Jersey,Male,All Ages,2022.0,8.0,133.0,3048.0,162.0,40.0,NaN,256.0
86564,09/01/2022,09/30/2022,New Jersey,Male,All Ages,2022.0,9.0,106.0,3111.0,193.0,42.0,NaN,258.0
86615,10/01/2022,10/31/2022,New Jersey,Male,All Ages,2022.0,10.0,140.0,3303.0,222.0,55.0,NaN,313.0
86666,11/01/2022,11/30/2022,New Jersey,Male,All Ages,2022.0,11.0,164.0,3283.0,241.0,60.0,15.0,359.0
86717,12/01/2022,12/31/2022,New Jersey,Male,All Ages,2022.0,12.0,214.0,3725.0,256.0,79.0,31.0,420.0
86768,01/01/2023,01/31/2023,New Jersey,Male,All Ages,2023.0,1.0,220.0,3463.0,244.0,79.0,19.0,403.0
86819,02/01/2023,02/28/2023,New Jersey,Male,All Ages,2023.0,2.0,130.0,3001.0,186.0,49.0,NaN,269.0
86870,03/01/2023,03/31/2023,New Jersey,Male,All Ages,2023.0,3.0,106.0,3221.0,189.0,40.0,0.0,255.0
86921,04/01/2023,04/30/2023,New Jersey,Male,All Ages,2023.0,4.0,42.0,3060.0,182.0,12.0,NaN,215.0
86972,05/01/2023,05/31/2023,New Jersey,Male,All Ages,2023.0,5.0,27.0,3031.0,159.0,NaN,NaN,179.0
87023,06/01/2023,06/30/2023,New Jersey,Male,All Ages,2023.0,6.0,24.0,2973.0,140.0,NaN,NaN,158.0
87074,07/01/2023,07/31/2023,New Jersey,Male,All Ages,2023.0,7.0,30.0,2907.0,133.0,NaN,0.0,154.0
87125,08/01/2023,08/31/2023,New Jersey,Male,All Ages,2023.0,8.0,42.0,2946.0,144.0,18.0,NaN,170.0
87176,09/01/2023,09/23/2023,New Jersey,Male,All Ages,2023.0,9.0,44.0,1735.0,103.0,17.0,0.0,130.0

In [53]:
total_mcovid_deaths.reset_index(inplace = True)

total_mcovid_deaths

,index,Start Date,End Date,State,Sex,Age Group,Year,Month,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Pneumonia and COVID-19 Deaths,Influenza Deaths,"Pneumonia, Influenza, or COVID-19 Deaths"
0,1598,01/01/2020,09/23/2023,New Jersey,Male,All Ages,NaN,NaN,19376.0,158472.0,17012.0,9677.0,188.0,26886.0
1,9095,01/01/2020,12/31/2020,New Jersey,Male,All Ages,2020.0,NaN,9881.0,48588.0,7353.0,4981.0,92.0,12338.0
2,9146,01/01/2021,12/31/2021,New Jersey,Male,All Ages,2021.0,NaN,5340.0,42570.0,4787.0,2871.0,NaN,7257.0
3,9197,01/01/2022,12/31/2022,New Jersey,Male,All Ages,2022.0,NaN,3490.0,40977.0,3392.0,1585.0,66.0,5358.0
4,9248,01/01/2023,09/23/2023,New Jersey,Male,All Ages,2023.0,NaN,665.0,26337.0,1480.0,240.0,29.0,1933.0
5,84932,01/01/2020,01/31/2020,New Jersey,Male,All Ages,2020.0,1.0,0.0,3444.0,199.0,0.0,24.0,223.0
6,84983,02/01/2020,02/29/2020,New Jersey,Male,All Ages,2020.0,2.0,0.0,3007.0,176.0,0.0,28.0,204.0
7,85034,03/01/2020,03/31/2020,New Jersey,Male,All Ages,2020.0,3.0,413.0,4047.0,489.0,214.0,24.0,711.0
8,85085,04/01/2020,04/30/2020,New Jersey,Male,All Ages,2020.0,4.0,4900.0,9317.0,2905.0,2438.0,13.0,5375.0
9,85136,05/01/2020,05/31/2020,New Jersey,Male,All Ages,2020.0,5.0,1718.0,4911.0,1084.0,886.0,NaN,1918.0
10,85187,06/01/2020,06/30/2020,New Jersey,Male,All Ages,2020.0,6.0,389.0,3175.0,309.0,176.0,0.0,522.0
11,85238,07/01/2020,07/31/2020,New Jersey,Male,All Ages,2020.0,7.0,187.0,3108.0,222.0,82.0,0.0,327.0
12,85289,08/01/2020,08/31/2020,New Jersey,Male,All Ages,2020.0,8.0,86.0,2976.0,167.0,38.0,0.0,215.0
13,85340,09/01/2020,09/30/2020,New Jersey,Male,All Ages,2020.0,9.0,83.0,2969.0,202.0,41.0,0.0,244.0
14,85391,10/01/2020,10/31/2020,New Jersey,Male,All Ages,2020.0,10.0,138.0,3146.0,220.0,64.0,0.0,294.0
15,85442,11/01/2020,11/30/2020,New Jersey,Male,All Ages,2020.0,11.0,580.0,3718.0,454.0,302.0,0.0,732.0
16,85493,12/01/2020,12/31/2020,New Jersey,Male,All Ages,2020.0,12.0,1387.0,4770.0,926.0,740.0,NaN,1573.0
17,85544,01/01/2021,01/31/2021,New Jersey,Male,All Ages,2021.0,1.0,1384.0,4706.0,945.0,752.0,0.0,1577.0
18,85595,02/01/2021,02/28/2021,New Jersey,Male,All Ages,2021.0,2.0,840.0,3883.0,596.0,440.0,0.0,996.0
19,85646,03/01/2021,03/31/2021,New Jersey,Male,All Ages,2021.0,3.0,560.0,3744.0,446.0,285.0,0.0,721.0
20,85697,04/01/2021,04/30/2021,New Jersey,Male,All Ages,2021.0,4.0,556.0,3604.0,447.0,305.0,0.0,698.0
21,85748,05/01/2021,05/31/2021,New Jersey,Male,All Ages,2021.0,5.0,282.0,3164.0,283.0,143.0,NaN,423.0
22,85799,06/01/2021,06/30/2021,New Jersey,Male,All Ages,2021.0,6.0,88.0,3110.0,168.0,43.0,0.0,213.0
23,85850,07/01/2021,07/31/2021,New Jersey,Male,All Ages,2021.0,7.0,66.0,2973.0,190.0,41.0,0.0,215.0
24,85901,08/01/2021,08/31/2021,New Jersey,Male,All Ages,2021.0,8.0,187.0,3227.0,247.0,95.0,0.0,339.0
25,85952,09/01/2021,09/30/2021,New Jersey,Male,All Ages,2021.0,9.0,349.0,3345.0,388.0,222.0,0.0,515.0
26,86003,10/01/2021,10/31/2021,New Jersey,Male,All Ages,2021.0,10.0,300.0,3537.0,369.0,176.0,0.0,493.0
27,86054,11/01/2021,11/30/2021,New Jersey,Male,All Ages,2021.0,11.0,199.0,3353.0,290.0,105.0,0.0,384.0
28,86105,12/01/2021,12/31/2021,New Jersey,Male,All Ages,2021.0,12.0,529.0,3924.0,418.0,264.0,0.0,683.0
29,86156,01/01/2022,01/31/2022,New Jersey,Male,All Ages,2022.0,1.0,1680.0,5350.0,1031.0,857.0,NaN,1854.0
30,86207,02/01/2022,02/28/2022,New Jersey,Male,All Ages,2022.0,2.0,474.0,3469.0,409.0,250.0,NaN,636.0
31,86258,03/01/2022,03/31/2022,New Jersey,Male,All Ages,2022.0,3.0,113.0,3225.0,187.0,53.0,0.0,247.0
32,86309,04/01/2022,04/30/2022,New Jersey,Male,All Ages,2022.0,4.0,83.0,3035.0,174.0,28.0,0.0,229.0
33,86360,05/01/2022,05/31/2022,New Jersey,Male,All Ages,2022.0,5.0,143.0,3249.0,175.0,46.0,NaN,276.0
34,86411,06/01/2022,06/30/2022,New Jersey,Male,All Ages,2022.0,6.0,105.0,2995.0,176.0,42.0,NaN,240.0
35,86462,07/01/2022,07/31/2022,New Jersey,Male,All Ages,2022.0,7.0,135.0,3184.0,166.0,33.0,NaN,270.0
36,86513,08/01/2022,08/31/2022,New Jersey,Male,All Ages,2022.0,8.0,133.0,3048.0,162.0,40.0,NaN,256.0
37,86564,09/01/2022,09/30/2022,New Jersey,Male,All Ages,2022.0,9.0,106.0,3111.0,193.0,42.0,NaN,258.0
38,86615,10/01/2022,10/31/2022,New Jersey,Male,All Ages,2022.0,10.0,140.0,3303.0,222.0,55.0,NaN,313.0
39,86666,11/01/2022,11/30/2022,New Jersey,Male,All Ages,2022.0,11.0,164.0,3283.0,241.0,60.0,15.0,359.0
40,86717,12/01/2022,12/31/2022,New Jersey,Male,All Ages,2022.0,12.0,214.0,3725.0,256.0,79.0,31.0,420.0
41,86768,01/01/2023,01/31/2023,New Jersey,Male,All Ages,2023.0,1.0,220.0,3463.0,244.0,79.0,19.0,403.0
42,86819,02/01/2023,02/28/2023,New Jersey,Male,All Ages,2023.0,2.0,130.0,3001.0,186.0,49.0,NaN,269.0
43,86870,03/01/2023,03/31/2023,New Jersey,Male,All Ages,2023.0,3.0,106.0,3221.0,189.0,40.0,0.0,255.0
44,86921,04/01/2023,04/30/2023,New Jersey,Male,All Ages,2023.0,4.0,42.0,3060.0,182.0,12.0,NaN,215.0
45,86972,05/01/2023,05/31/2023,New Jersey,Male,All Ages,2023.0,5.0,27.0,3031.0,159.0,NaN,NaN,179.0
46,87023,06/01/2023,06/30/2023,New Jersey,Male,All Ages,2023.0,6.0,24.0,2973.0,140.0,NaN,NaN,158.0
47,87074,07/01/2023,07/31/2023,New Jersey,Male,All Ages,2023.0,7.0,30.0,2907.0,133.0,NaN,0.0,154.0
48,87125,08/01/2023,08/31/2023,New Jersey,Male,All Ages,2023.0,8.0,42.0,2946.0,144.0,18.0,NaN,170.0
49,87176,09/01/2023,09/23/2023,New Jersey,Male,All Ages,2023.0,9.0,44.0,1735.0,103.0,17.0,0.0,130.0

In [ ]:
mdeaths_by_year